project:
  type: book
  output-dir: docs

execute:
  freeze: auto

bibliography: references.bib

book:
  title: "FMBA AI Workshop Jan 2026"
  author: "Yuan Tian"
  date: today
  chapters:
    - index.qmd
    - chapter0.qmd
    - chapter1.qmd
    - chapter2.qmd
    - chapter3.qmd
    - chapter4.qmd

format:
  html:
    theme:
#      - sandstone
      - brite
#      - minty
#      - flatly
#      - brand
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: true
    code-summary: "Click to expand/collapse"
  pdf:
    documentclass: scrreprt

